### ISSUE TITLE
Polymorphism question, relating to upcoming API change

### ISSUE THREAD

**Issue by issackelly** [chriskuchin/terraform-provider-bowtie#5]
We are starting to build out automatic update logic in the UI. Some of it exists in the controller now, controllable by writing rules on the filesystem but we would like that to be more streamlined. 

To the `controller` object we are adding a new field: "version_strategy".

That can take one of four values at the moment. I would like to know if this sort of polymorphism in the value is a pain for you.

Here are all four, I'm fishing for opinions.

```
{"controllers": "<some uuid>": {
    "version_strategy": "manual" // default
    "version_strategy": {"specific": "23.09.001"} // a tagged release
    "version_strategy": {"newest-at-interval": "24h"} // check every 24h
    "version_strategy": {"newest-at-calendar": "03:00"} // check at 3AM
    }}
```

I could also avoid polymorphism and do something more like this. This seems worse to me as a javascript API but better for OpenAPI and probably better for your Go bindings. 

```
{"controllers": "<some uuid>": {
    "version_strategy": {"type": "manual", "value": null} // default
    "version_strategy": {"type": "specific", "value": "23.09.001"} // a tagged release
    "version_strategy": {"type": "newest-at-interval", "value": "24h"} // check every 24h
    "version_strategy": {"type": "newest-at-calendar", "value": "03:00"} // check at 3AM
    }}
```

**Comment by chriskuchin** [comment]
in your first example I could do easily everything but the object -> string differences. So manual would be tricky. If you did something similar to the others like `{"manual": true}` or similar where version_strategy is always an object.

or something like 

```
{
   "type": "manual|specific|newest-at-interval|newest-at-calendar"
   "value: "etc..."
}
```

Might be simplest to handle

and my example is exactly your second example. Except I would just omit value on manual. Handling the polymorphism would be ugly honestly.

**Comment by issackelly** [comment]
Thanks. That's exactly what I was thinking, Second example is better for this case where you're casting into structs for sure. I'll go with the latter.
